/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    signing
    `java-library`
    `maven-publish`
    kotlin("jvm")
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.jda)
    implementation(libs.webhooks)
    implementation(libs.json)
    implementation(libs.postgres)
    implementation("com.github.twitch4j:twitch4j:1.20.0")
    implementation(libs.twitch4j.reactor)
    implementation(libs.youtube)
    implementation(libs.logback)
    implementation(libs.slf4j)
    implementation(libs.hikari)
    implementation(libs.hibernate.core)
    implementation(libs.hibernate.hikari)
    implementation(libs.flyway)
    implementation(libs.spring.web)
    implementation(libs.spring.boot)
    implementation(libs.spring.boot.autoconfigure)
    implementation(libs.tomcat.starter)
    implementation(libs.spring.actuator)
    implementation(libs.spring.data.rest)
    implementation(libs.okhttp)
    implementation(libs.kotlin)

    compileOnly(libs.jetbrains.annotations)


}

group = "de.sparkarmy"
version = "2.0-SNAPSHOT"
description = "SparkArmyBot"

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
kotlin {
    jvmToolchain(21)
}